### ISSUE TITLE
Delegated establishment event persistence

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/keripy#100]
A local Habitat should save a delegated establishment events after signing it and before receiving the anchoring event from the delegating identifier.  Currently the delegated inception event is held locally in escrow.  This causes issues with communication and processing of the delegating identifiers anchor.

**Comment by SmithSamuelM** [comment]
The local KEL  of the delegatee can accept a fully signed delegated event because the delegate has committed to it. It does not need to wait for the delegator to anchor it. This changes the local logic of delegated events wrt to delegate.

**Comment by SmithSamuelM** [comment]
Witness of delegate may also enter the fully signed delegated event in their KEL before its anchored in delegators key.

**Comment by blelump** [comment]
Can you guys clarify what (local) Habitat is, or point to some glossary?

**Comment by SmithSamuelM** [comment]
In the python code, the Habitat is the name of the object class that manages the information associated with an AID. Its not part of the KERI protocol per se. So better would be to say that the KEL for a delegate controller may accept the delegated event before proof of its anchor in the delegator's key has been received by the delegate but after it has been fully signed by the delegate's private key(s)
