### ISSUE TITLE
Add said `d` field to all KERI event messages (icp, rot, dip, drt)

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#110]
Tracking the implementation of:

https://hackmd.io/XfdKjT3ZQDi1M6Iv3iYhbg

**Comment by SmithSamuelM** [comment]
# Messages Field Order Changes

Because adding the `d` field SAID to every key event message type will break all the explicit test vectors. Its no additional pain to normalize the field ordering across all message types and seals.
Originally all messages included an `i` field but that is not true any more. So the changed field ordering is to put the fields that are common to all message types first in order followed by fields that are not common. The common fields are `v`, `t`, `d`.
The newly revised messages and seals are shown below.

## Event Messages

### Inception Event
When the AID in the `i` field is a self-addressing self-certifying AID, the new Inception Event has two
derived digest fields. In this case both the `d` and `i` fields must have the same value. This means the digest suite's derivation code, used for the `i` field must be the same for the `d` field.
The derivation of the `d` and `i` fields is special. Both the `d` and `i` fields are replaced with dummy `#` characters of the length of the digest to be used. The digest of the Inception event is then computed and both the `d` and `i` fields are replaced with the fully qualified digest value. Validation of an inception event requires examining the `i` field's derivation code and if it is a digest type then the `d` field must be identical otherwise the inception event is invalid.

When the AID is not self-addressing, i.e. the `i` field  derivation code is not a digest. Then the `i` is given its value and the `d` field is replaced with dummy characters `#` of the correct length and then the digest is computed. This is the standard SAID algorithm.


```json
{
  "v" : "KERI10JSON00011c_",
  "t" : "icp",
  "d" : "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i" : "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM",
  "s" : "0",
  "kt": "1",
  "k" : ["DaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],
  "n" : "EZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "bt": "1",
  "b" : ["DTNZH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8JZAo5CM"],
  "c" : ["EO"],
  "a" :[]
}
```



### Basic Rotation Event  (also delegating rotation)

```json
{
  "v" : "KERI10JSON00011c_",
  "t" :  "rot",
  "d" :  "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i" :  "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM",
  "s" : "1",
  "p" : "EULvaU6JR2nmwyZ-i0d8JZAoTNZH3YAfSVPzhzS6b5CM",
  "kt" :  "1",
  "k" :  ["EaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],
  "n" :  "EYAfSVPzhzZ-i0d8JZAoTNZH3ULvaU6JR2nmwyS6b5CM",
  "bt":  "1",
  "ba":  ["DTNZH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8JZAo5CM"],
  "br":  ["DH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8TNZJZAo5CM"],
  "a" :[]
}
```


### Partial Rotation Event
```json
{
  "v" : "KERI10JSON00011c_",
  "t" : "ort",
  "d" : "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i" : "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM",
  "s" : "1",
  "p" : "EULvaU6JR2nmwyZ-i0d8JZAoTNZH3YAfSVPzhzS6b5CM",
  "kt": "2",
  "k" :  
    [
      "Ed8JZAoTNZaU6JR2nmwyZ-i0H3ULvYAfSVPzhzS6b5CM",
      "Ed8JZAoTNZaU6JR2nmwyZ-i0H3ULvYAfSVPzhzS6b5CM",
      "Ed8JZAoTNZaU6JR2nmwyZ-i0H3ULvYAfSVPzhzS6b5CM"
    ],
  "ot": "3",
  "o" : 
    [
      "ETNZH3ULvYaU6JR2nmwyZ-i0d8JZAoAfSVPzhzS6b5CM", 
      "EYAfSVPzhzaU6JR2nmwyZ-i0d8JZAoTNZH3ULvS6b5CM"
    ]
  "n" : "EYAfSVPzhzZ-i0d8JZAoTNZH3ULvaU6JR2nmwyS6b5CM",
  "bt": "1",
  "ba": ["DTNZH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8JZAo5CM"],
  "br": ["DH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8TNZJZAo5CM"],
  "a" : []
}
```


### Interaction Event  (Also delegating Interaction)

```json
{
  "v": "KERI10JSON00011c_",
  "t": "isn",
  "d": "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i": "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM",
  "s": "2",
  "p": "EULvaU6JR2nmwyZ-i0d8JZAoTNZH3YAfSVPzhzS6b5CM",
  "a":
  [
    {
      "d": "ELvaU6Z-i0d8JJR2nmwyYAZAoTNZH3UfSVPzhzS6b5CM",
      "i": "EJJR2nmwyYAfSVPzhzS6b5CMZAoTNZH3ULvaU6Z-i0d8",
      "s": "1"
    }
  ]
}
```

### Delegated Inception Event

```json
{
  "v" : "KERI10JSON00011c_",
  "t" : "dip",
  "d" : "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i" : "EJJR2nmwyYAfSVPzhzS6b5CMZAoTNZH3ULvaU6Z-i0d8",
  "s" : "0",
  "t" : "dip",
  "kt": "1",
  "k" : ["DaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],
  "n" : "EZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "bt": "1",
  "b" : ["DTNZH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8JZAo5CM"],
  "c" : ["DND"],
  "a" : [],
  "di": "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM"      
}

```

### Basic Delegated Rotation Event

```json
{
  "v" : "KERI10JSON00011c_",
  "t" : "drt",
  "d" : "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i" : "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM",
  "s" : "1",
  "p" : "EULvaU6JR2nmwyZ-i0d8JZAoTNZH3YAfSVPzhzS6b5CM",
  "kt": "1",
  "k" : ["EaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM"],
  "n" : "EYAfSVPzhzZ-i0d8JZAoTNZH3ULvaU6JR2nmwyS6b5CM",
  "bt": "1",
  "ba": ["DTNZH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8JZAo5CM"],
  "br": ["DH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8TNZJZAo5CM"],
  "a" : []
  "di": "EJJR2nmwyYAZAoTNZH3ULvaU6Z-i0d8fSVPzhzS6b5CM"
}
```



## Delegated Partial Rotation Event

```json
{
  "v" : "KERI10JSON00011c_",
  "t" : "dor",
  "d" : "E0d8JJR2nmwyYAfZAoTNZH3ULvaU6Z-iSVPzhzS6b5CM",
  "i" : "EZAoTNZH3ULvaU6Z-i0d8JJR2nmwyYAfSVPzhzS6b5CM",
  "s" : "1",
  "p" : "EULvaU6JR2nmwyZ-i0d8JZAoTNZH3YAfSVPzhzS6b5CM",
  "kt": "2",
  "k" :  
    [
      "Ed8JZAoTNZaU6JR2nmwyZ-i0H3ULvYAfSVPzhzS6b5CM",
      "Ed8JZAoTNZaU6JR2nmwyZ-i0H3ULvYAfSVPzhzS6b5CM",
      "Ed8JZAoTNZaU6JR2nmwyZ-i0H3ULvYAfSVPzhzS6b5CM"
    ],
  "ot": "3",
  "o": 
    [
      "ETNZH3ULvYaU6JR2nmwyZ-i0d8JZAoAfSVPzhzS6b5CM", 
      "EYAfSVPzhzaU6JR2nmwyZ-i0d8JZAoTNZH3ULvS6b5CM"
    ]
  "n" : "EYAfSVPzhzZ-i0d8JZAoTNZH3ULvaU6JR2nmwyS6b5CM",
  "bt": "1",
  "ba":  ["DTNZH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8JZAo5CM"],
  "br":  ["DH3ULvaU6JR2nmwyYAfSVPzhzS6bZ-i0d8TNZJZAo5CM"],
  "a" :[]
  "di" : "EJJR2nmwyYAZAoTNZH3ULvaU6Z-i0d8fSVPzhzS6b5CM"
}
```


## Receipts
### Non-Transferable Prefix Signer Receipt
For receipts the `d` field is the SAID of the asssociated event not the receipt message itself.

```json
{
  "v": "KERI10JSON00011c_",
  "t": "rct",
  "d": "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "i": "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
  "s": "1"
}
```

### Transferable Prefix Signer Receipt
For receipts the `d` field is the SAID of the asssociated event not the receipt message itself.
```json
{
  "v": "KERI10JSON00011c_",
  "t": "vrc",
  "d": "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
  "i": "AaU6JR2nmwyZ-i0d8JZAoTNZH3ULvYAfSVPzhzS6b5CM",
  "s": "1",
  "a":
    {
      "d": "DZ-i0d8JZAoTNZH3ULvaU6JR2nmwyYAfSVPzhzS6b5CM",
      "i": "AYAfSVPzhzS6b5CMaU6JR2nmwyZ-i0d8JZAoTNZH3ULv",
      "s": "4"
    }
}
```

## Seals

### Digest Seal

```json
{
  "d": "Eabcde..."
}
```

### Merkle Tree Root Digest Seal 

```json
{
  "rd": "Eabcde..."
}
```

## Registrar Seal

```json
{
  "d" : “EFGKDDA...",
  "bi": “BACDEFG...”
}

```

### Event Seal
```json
{
  "d": "Eabcde...",
  "i": "Ebietyi....",
  "s": "3"
}
```

### Event location Seal
deprecated no longer used anywhere

```json
{
  "t":  "ixn",
  "i": "Ebietyi....",
  "s": "3",
  "p": "Eabcde..."
}
```

**Comment by blelump** [comment]
Sometimes it is not easy to find the meaning behind given label. I am aware there is a table https://hackmd.io/lb3nW_e5Sle3BXo4G4QP9Q#KERI-Defined-Element-Labels and I would propose to further extend it, but also sort it in the lexical order, as opposed to canonical form of the messages as it increases the readability of the table when looking for smth. I can address that.

**Comment by SmithSamuelM** [comment]
# SAIDs and KERI Label Convention Normalization


Because order of appearance of fields is enforced then where a label appears can add context to help
clarify its meansing.  

`v` for version string when. it appears must be the first field

We have two other identifiers that appear after `v` when `v` is present or may appear first
when `v` is not present. These are `i` and `d`. 

In this context, `i` is short for `ai`, the attributable identifier (controller identifier prefix).
The attributable identifier may also be though of as the the autonomic identifier, the attesting identifier (testator), the authorizing identifier, the author identifier, and the authenticated identifier. A way of thinking about an `i` or `ai` is that it is the identifier of the authoritative entity to which a statement may be securely attributed, thereby making the statement verifiably authentic.




## KERI Defined Element Labels

|Label|Description|Type|Notes|
|---|---|---|---|
|v| Version String| | |
|i| Identifier Prefix|  | |
|s| Sequence Number|  | |
|t| Message Type| | |
|te| Last received Event Message Type in Key State Notice | | |
|d| Event Digest (Seal or Receipt or Key State Notice) ||
|p| Prior Event Digest | | |
|kt| Keys Signing Threshold || |
|k| List of Signing Keys (ordered key set)| | |
|n| Next Key Set Commitment |   | |
|bt| Backer Threshold || |
|b| List of Backers  (ordered backer set) | | |
|br| List of Witnesses to Remove (ordered witness set) | | |
|ba| List of Witnesses to Add (ordered witness set) | | |
|c| List of Configuration Traits/Modes |  | |
|a| List of Anchors (seals) || |
|da| Delegator Anchor Seal in Delegated Event (Location Seal) | | Obsolete |
|di| Delegator Identifier Prefix  | | |
|rd| Merkle Tree Root Digest || |
|ee| Last Establishment Event Map | | |
|vn| Version Number ("major.minor")  |  | |

A label may have different values in different contexts but not a different value ***type***.

## ACDC Proposed Element Labels



## Proposed Normalized Combined Element Labels



# Enhancement Proposal: Add SAID to Key Events in KERI
Future enhancement to KERI 

## Motivation Security
Given KERI design principle prioritization of security first, always over performance second and convenience third, when a mechanism presents itself that may improve security it is something to consider. That mechanism is SAIDs for events. Currently KERI events do not have SAIDs except for the inception event when the identifier prefix is self-addressing.  But all KERI events could have another field that is a SAID for that event.  Why this may improve security comes from the combination of two features of KELs. One is that events in a KEL are  hash (digest) chained together and KERI supports digest agility. The best way to detect uniqueness and duplicity of events is to use a cryptographic digest of the event to reason about the event. Another event with the same SN but with a different digest is easily determined to be different (potentially duplicitous). This same digest may be used as a database key to reference the event.  The problem is that each event must be digested in order to be stored. Receipts on that event all digest the event to indicate compactly which event is being receipted in a cryptographically secure way.  A subsequent event also uses a hash to chain itself to a prior event. Each of these three hashes may be different. This is because there is no normative digest for an event. The controller of that KEL may change the digest algorithm it uses from one event to the next. So a prior event digest is not indicative or constraining of the next event digest. Each receipter also may choose its own digest. The result is that a given validator must do digest comparisons to ascertain if a given digest is for the same event when those digests use a different cipher suite or digest algorithm. This comparison operation  shows up in many places in the code. It would be easy to get it wrong or miss a place where a comparison should be done simply because the default digest algorithm is in use by all three participants, namely, validator indexing event with digest, receipter indexing event, controller chaining event. We can call this potential digest confusion due to digest agility.

When KERI was originally conceived the idea of a SAID for each event was not considered. The concept of a generic SAID to make schema and ACDC immutable and to make it easier to reason securely about immutable data may be back ported to KERI events. Ironically the SAID is a broader application of self-addressing self-certifying identifiers originally developed for KERI inception events. But that concept was not applied to other events besides the inception. The problem of digest agility and the need for digest comparison was discovered later when implementing KERI validation logic.

The proposed enhancement for security reasons would be to include a SAID in every KERI event. This makes a given digest normative for that event and is determined by the controller of the KEL to which that event belongs. All digests in other events, in seals,  in receipts, and in attachmentss for that reference that  event would then use that normative said. This means there would no longer be a potential for digest confusion.  There is one normative digest for a given event and that is the SAID of that event.

## Analysis
Digest agility is still supported but limited in the sense that when an event is first created the SAID for that event may use a different digest algorithm from that used by previous events. But the prior event digest in a new event must use the SAID defined in the prior event.  

Impact on performance:  This proposal hurts performane because each event gets an additional field. Given 32 byte digests this adds an average of 35 bytes to each event. The trade-off is simpler validator code logic which could help avoid security problems.  

This proposal, however, does provide a mechanism for improving performance.  Given that each event has a SAID then an alternative compact means for transferring a KEL becomes possible. Instead of including the event data in the body, only the SAID is included in the body and the body is included as an optional attachement. The body could be cached, or optionally transmitted when not cached. This could on average result in significant bandwidth savings in when multiple hosts are sharing KELs and there is redundant sharing.

Impact on convenience: This proposal helps convenience because all the code everywhere would use the same digest (SAID) to reason about events.



## Label Normalization
Given that ACDC and Schema use SAIDs the convention for which field labels to use may be worth considering so as to minimize confusion down the road should SAIDs be added to KERI events.


Current label conventions:

KERI events:

`i`  SCID KEL prefix AID
`p`  prior digest  -> prior SAID
`d` event digest -> event SAID

The conflict is that in a Schema or VC we have the convention of using `i` for the current data SAID which conficts with the  prefix in a KERI event

Authentic Data
`i`  SAID 
`ti` testator id AID
`si`  subject ID AID
`d`  data
`p` payload

Some other terminology suggestions

Secure Attribution implies an attributed identifier or `ai`  this is equivalent to an `AID`  its just that we can use two words for `a`, autonomic or attributed they both convey and important meaning.

`ai`

Instead of `s` for sources  in ACDC we could use `p` for priors  this is the same sense that we use `p` in KERI for chaining to the prior event,  where could have a priors array in ACDC that chains to prior ACDCs.

Instead of `d` for data we could use `a` for attributes   



Here is a list of current usages for reference
`i`  identifier SCID AID 
`i` SAID  (potential collision)
`ai` attribution identifier NOT a SAID must be SCID AID
`ti`  testator ID NOT a SAID must be SCID AID
`si` subject ID NOT a SAID must be SCID AID
`si`   SAID (potential collision

`di` delegator ID NOT a SAID must be SCID AID
`ci` certified ID  as in SCID or AID


## Proposed Normalization

`v` is version
`d` is said everywhere
`a` is attributes data anchors data 
`p` is provenance include prior events and chained events and chained acdc sources
`i` is a keri identifier prefix testator id and subject id AID
`s` is schema
`t` is type
