### ISSUE TITLE
KSN Message refactor as attribute section of new reply message

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#114]
The fields that are already in the reply message may be deleted from the existing KSN in terms of the fields from the KSN that go into the attributes field of the reply.

Likewise the KSN that is used for storing the latest key state for the Kever so it can be simplified since its no longer an over the wire structure.

After our call I thought about the KSN escrow database artifacts.
So to be clear I am talking about the new KSN that is actually embedded in the rpy message.

Unlike the service endpoints, KSN replies serve a temporary function that is obsoleted as soon as the events noticed by the KSN are accepted into the appropriate KEL. There is no replay attack vulnerability in that case
because the logic is to first check the Kever (KEL) state to see if it has already been accepted and then and only then go through the ksn query and then ksn reply. This means that the ksn reply should have a clean up or prune process (Doer) that runs periodically to prune the branches of the ksn reply escrows. The reason for this is that given multiple sources for a ksn for a given AID there may be multiple sources but only the source that gets accepted may be known at the time of acceptance. To reiterate once the key events are accepted into the KEL the KSN reply escrow is moot and may be deleted. Othewise the database will grow without bound.

**Comment by pfeairheller** [comment]
Closed with PR #117
