### ISSUE TITLE
Tried to install Keripy following instructions in readme.me

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/keripy#137]
The installation runs smooth on a Mac OSX (see attachment for details)

But in the end I get two errors I can't decipher. See attachments.

<img width="496" alt="Screenshot 2022-01-27 at 16 35 59" src="https://user-images.githubusercontent.com/479356/151391425-a3ae7ccc-2d2c-46d0-b2d9-47a470d60473.png">
<img width="893" alt="Screenshot 2022-01-27 at 16 33 55" src="https://user-images.githubusercontent.com/479356/151391434-e5959d42-250e-41d2-a78e-333c103f5d5e.png">
<img width="874" alt="Screenshot 2022-01-27 at 16 31 31" src="https://user-images.githubusercontent.com/479356/151391437-ed519e17-02c5-48c1-9787-51890a186fe6.png">

My goal is to set up a test and demo environment and present how KERI works to others like Phil did for IIW.

**Comment by m00sey** [comment]
What is the output of `python3 --version`?

**Comment by henkvancann** [comment]
(keripy) hvc@Henks-Mbp20 keripy-1 % python3 --version
Python 3.9.5

**Comment by m00sey** [comment]
so I would start by updating to 3.9.7 this is required by keripy
https://github.com/WebOfTrust/keripy/blob/0491dad8c589d5214253941d93b81847ea11703c/setup.py#L71

we use `pyenv` to manage python versions, that will fix the second issue.

**Comment by henkvancann** [comment]
Thx, Kevin, the guideline said "python 3.9.1+", but I'll try and fix it.

pyenv -> do I need to install this, or just call it? Both? Any switches?

**Comment by m00sey** [comment]
`pyenv install 3.9.7`

then you can set it for a specific local directory, so when inside keripy you could do:

`pyenv local 3.9.7`

which will leave your system python alone.

**Comment by henkvancann** [comment]
With regard to the python version, something I can't grasp is going on:

hvc@Henks-Mbp20 keri-1 % python3 -m venv keripy
hvc@Henks-Mbp20 keri-1 % source keripy/bin/activate
(keripy) hvc@Henks-Mbp20 keri-1 % python3 --version
Python 3.9.5
(keripy) hvc@Henks-Mbp20 keri-1 % brew upgrade python
Warning: python 3.9.10 already installed
(keripy) hvc@Henks-Mbp20 keri-1 %

**Comment by m00sey** [comment]
Managing multiple installations of python can be a pain. 

That is why we use pyenv.

**Comment by henkvancann** [comment]
I've installed peen, read the documentation, followed the guidelines...

(keripy) hvc@Henks-Mbp20 keripy-1 % source keripy/bin/activate     
(keripy) hvc@Henks-Mbp20 keripy-1 % pyenv local 3.9.7              
(keripy) hvc@Henks-Mbp20 keripy-1 % python3 --version              
Python 3.9.5

It wasn't meant to be :) I don't want to be learning pyenvs, I'd like to work with keri.
Thx, for your tries, Kevin. I'll wait for a readily available test Docker container with everything tested and working?
