### ISSUE TITLE
New format for next and next threshold in Establishment Events Enables Partial Rotation of all Rotation events

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#144]
The new format for establishment events is defined here
https://hackmd.io/Tfm63kdnRdmGxcVgrne5Uw

## Additional validation logic by multi-sig group members prior to signing.
 - Ensure that digest of next public key is included in next digest list, `n` field  before signing if the group member expects to be part of the next set of signers. Add a flag to the event signing method to indicate this expectation. A group member may willingly expect to be part of the next set of signers if they are transferring control of the identifier to someone else and would still sign. But if they are expecting to part of the next set of signers and their public key digest does not show up in the next list then it may a surreptitious  attempt to wrest control away from them and they should not sign.
- Update UX/UI to display the result of this check prior to signing to allows signer to indicate willingness to sign in spite of no longer being included.

## Additional validation logic for rotation event
- Ensure that set of signatures satisfies both the previous next threshold `nt` from previous est event and the current key threshold `kt` of current rotation event being validated. Support for partial rotation means that prior `nt` and current `kt` do not have to be the same but must be both satisfiable. Prior `nt` must be satisfied by a subset of the public keys committed to in the prior `n` field list. Current `kt` must be satisfied by a superset composed of the prior `nt` satisfycing set combined with any additional needed public keys from current `k`.  

## Multi-sig group membership
There are two classes of members in a multi-sig group. 

A)  Member of the current set of signing keys, i.e. public key in `k` field list
B)  Member of the next set of signing keys, i.e. public key in `n` field list

A Member may be in both A and B or in only one of A or B.  Membership in B means ultimate authority because only members of B may participate in the next rotation event which may change membership of both A and B. Membership only in A means current signing authority only  and no authority to rotate.

In addition a former Member may be thought of as having Alumni status once removed from a multi-sig group but no longer has any authority over the identifier controlled by the multi-sig group

The UX/UI for a given establishment event may want to indicate the group membership status and any proposed change in status prior to approving a new proposed establishment event.

**Comment by pfeairheller** [comment]
Closed with PR #146
