### ISSUE TITLE
Demo directory contains lots of stuff that doesn't meet the syntax requirements of KLI

### ISSUE THREAD

**Issue by paulfdietrich** [WebOfTrust/keripy#156]
Some familiarity with KERI and KLI.

Installed in virtualenv, and ran the test cases and generally the library work great. Thanks so much.

demo-script.sh does run and seems to report what I would expect.

Now I'm Trying to learn the detail of controllers witnesses and watchers, but lots of demo samples don't really run due to API mismatch. Looks like KLI syntax has changed and these need updating.  If someone want to give me a digest of what changed, I don't mind creating the  PR.

For example. Below I ran start_agent.sh (after init)

$ kli init --name gleif --nopasscode
KERI Keystore created at: /usr/local/var/keri/ks/gleif
KERI Database created at: /usr/local/var/keri/db/gleif
KERI Credential Store created at: /usr/local/var/keri/reg/gleif

$ ./scripts/demo/start-agent.sh 
Identifier prefix does not exist, running incept
usage: kli incept [-h] --name NAME [--base BASE] --alias ALIAS [--config CONFIG] --file FILE [--passcode BRAN] [--aeid AEID]
kli incept: error: the following arguments are required: --alias/-a
usage: kli vc registry incept [-h] --name NAME [--registry-name REGISTRY_NAME] [--no-backers NO_BACKERS] [--backers <prefix>]
                              [--establishment-only ESTABLISHMENT_ONLY] [--base BASE] --alias ALIAS [--passcode BRAN]
kli vc registry incept: error: the following arguments are required: --alias/-a
usage: kli [-h] command ...
kli: error: unrecognized arguments: --name gleif

It seems like name and alias have gone through some transformation, but its not always  clear in the KLI commands whether name is the name of the database and keystore  or a new name for what I am creating.

**Comment by pfeairheller** [comment]
Yes, the demo directory has accumulated some cruft that was not properly culled when the `kli` was updated.

I will remove or update the shell scripts over the next couple of days.
