### ISSUE TITLE
Gossip protocol

### ISSUE THREAD

**Issue by blelump** [WebOfTrust/keripy#158]
Let me introduce some initial thoughts into the information dissemination via the gossip protocol. The thoughts collected below aren't complete and shall be further discussed.

### Discoverability

One of the next features to be addressed is gossiping, especially among witnesses and watcher network actors or just simply nodes. A node to gossip some information requires other nodes to gossip to. Here we have two cases:
* the overall amount of various node types (witnesses, watchers etc) are managed under federated model, where they're constrained to certain amount;
* the overall amount of various node types in the network is dynamic and nodes need to discover other nodes to gossip to.

Depending on the above assumptions, the problem space may be defined in a different way. Lets start then with the latter, so the dynamic amount of nodes. 

When node bootstraps for the first time, its `view` of other nodes is either empty or preconfigured (ie. coming from the node config) to a certain amount of other known nodes. However, a node must be also able to find out (or be notified about other nodes) where to gossip to. The easiest solution is to allow nodes to gossip their `view` of other nodes, so that when a new node joins the network, it first communicates with a node that already participates in the network. Later on this node gossips info about new node in the network. Nodes gossip info about other nodes in the form of OOBI's.

### Death detection

If the amount of nodes in the network is dynamic, we must assume new nodes may be established as well as existing nodes may be shutdown. To not gossip to a node that is already considered dead, some kind of death detection mechanism is needed. To be discussed.

### Recoverability

When a node goes out of sync with other nodes, ie. it lost the internet connection for some time, node needs to re-sync to get the latest data. Other nodes don't know in what state current node is and current node doesn't know how far behind it is comparing to the other nodes. Two approaches to consider:
* push/pull model, where nodes are able to gossip to each other to eventually converge;
* push model only, where other nodes are gossiping as usual, so that node who was offline awaits until there are some new gossips.

### What to gossip

There are several data types to be considered:
* witness receipts;
* identifiers KSN messages so that if the KEL changes, nodes are able to re-sync using the query mode.
* ?

### When to gossip

event driven gossiping mechanism, where node gossips to other nodes only if any new change has happened on his side, ie. new event appended into KEL/new receipt issued/...

### How to gossip

Nodes are gossiping via UDP protocol, so that they don't care whether the message has been delivered.

**Comment by SmithSamuelM** [comment]
The best-performing gossip protocols have both a push and pull phase or mode. In the early phase of a distribution, push is the most performant in the later phase pull becomes more performant.  The pull phase also nicely addresses the sync issue you bring up.

**Comment by blelump** [comment]
Sam, 

shall `pulls` ever be addressed via gossip? Query mode could be used to achieve similar outcome, so that no additional mechanism is required.

#### What to query problem

Either `pulls` or using existing `query mode`, if given node goes out of sync and considering there are plenty of data that is being gossip. Lets say a million of identifiers are established, gossiped and node goes out of sync for some time. As given node is operational again, to find out where it is out of sync is basically querying everything from other nodes, unless some other sophisticated mechanism exist.

**Comment by SmithSamuelM** [comment]
During the early phase of gossip  push (where gossiper’s randomly pick targets to gossip too) the efficiency of distribution is high. Once the gossip has reached over 50% of the targets, many of the gossips become redundant and the efficiency drops. There is a slow asymptomatic decline to reach full penetration. During this later phase it is more efficient to pull (query) likely targets to see if (1) they have already received the gossip (2) have a gossip that the puller has not yet received. So modern performant gossip protocols switch modes once their push mode efficiency drops below a threshold.

**Comment by blelump** [comment]
Sam,

```
Witnesses have an incentive to publish early and broadly so they may want a push mechanism to push their publications to watchers. But gossip with watchers by witnesses may not be the best approach.
```

to achieve it various approaches can be applied (or using various techniques). Putting this apart, shall any Watcher receive any information from Witness or she should be able to choose, ie. only a subset of identifiers that she's interested in?

Lets say I want to "subscribe" for updates in Witness so I sign (as a Watcher) a `qry` msg:
```
{
   ...
  "r" : "sub",
  "q" : 
  {
    identifiers: "*"    
  }
}
```
and therefore I get any notification. On the other hand I would like to only get a subset, so I sign:
```
{
   ...
  "r" : "sub",
  "q" : 
  {
    identifiers: [identifier1,identifier2,identifier2,]
  }
}
```
Does it make sense? Notice I sign `qry` msg to subscribe and it somehow doesn't sound right to me as OOBI would make more sense here.

Perhaps different approach would fit here better, so that I indeed issue OOBI as a Watcher and Witness upon accepting this OOBI simply sends me anything and it is on my shoulders to eventually filter in what identifiers I am interested in?

**Comment by blelump** [comment]
Closing this with the assumption that this makes sense:
```
Perhaps different approach would fit here better, so that I indeed issue OOBI as a Watcher and Witness 
upon accepting this OOBI simply sends me anything and it is on my shoulders to eventually filter 
in what identifiers I am interested in?
```

@SmithSamuelM if you'd have some additional thoughts, I'll appreciate them, thanks!

**Comment by SmithSamuelM** [comment]
In general you want to have access to a promiscuoous super watcher (juror) that is just recording the SAID of the latest event all all KELS and akso any SAIDs of duplicitous events.  This  type of watcher might keep an oobi of the witness but that is secondary.  What is does is establish first seen versions of all events. Your own watcher then checks the juror for duplicity and latest event. But then need only subscribe to the subset of kels  from witnesses it is actually trans acting with but is dafe from eclipse attack,

A super juror might have serveral terabytes in its database. Aids -> Latest event Saids of every AID globally.  This is much mote efficient than certificate transparency which needs a sparse merkle tree of every cert for every dns name not merely the Said of the larest event.  duplicity as a provable property removes the ambiguity inherent in certificate transparency
