### ISSUE TITLE
Return Value of sign Function

### ISSUE THREAD

**Issue by abhinavb1293** [WebOfTrust/keripy#18]
I tried using the sign function in the keeping.py file, but that function returns only the address of the object of either sigers or cigars. 
Can someone please explain, how to retrieve the list from that address?

Code is here: https://github.com/WebOfTrust/keripy/blob/dbbbcd19ba8ae7f85217c7e4aee01e1a6c8e944d/src/keri/app/keeping.py#L1335

def sign(self, ser, pubs=None, verfers=None, indexed=True, indices=None):
        """
        Returns list of signatures of ser if indexed as Sigers else as Cigars with
        .verfer assigned.
        Parameters:
            ser is bytes serialization to sign
            pubs is list of qb64 public keys to lookup private keys
            verfers is list of Verfers for public keys
            indexed is Boolean, True means use offset into pubs/verfers/signers
                for index and return Siger instances. False means return Cigar instances
            indices is list of int indexes (offsets) to use for indexed signatures
                that may differ from the order of appearance in the pubs or verfers
                lists. This allows witness indexed sigs or controller multi-sig
                where the parties do not share the same manager or ordering so
                the default ordering in pubs or verfers is wrong for the index.
                If provided the length of indices must match pubs/verfers/signers
                else raises ValueError. If not provided and indexed is True then use
                default index that is offset into pubs/verfers/signers
        if neither pubs or verfers provided then returns empty list of signatures
        If pubs then ignores verfers otherwise uses verferss
        Manager implement .sign method and tests
        sign(self,ser,pubs,indexed=True)
        checks for pris for pubs in db is not raises error
        then signs ser with eah pub
        returns list of sigers indexed else list of cigars if not
        """
        signers = []

        if pubs is None and verfers is None:
            raise ValueError("pubs or verfers required")

        if pubs:
            for pub in pubs:
                verfer = coring.Verfer(qb64=pub)  # needed to know if nontrans
                raw = self.keeper.getPri(key=pub)
                if raw is None:
                    raise ValueError("Missing prikey in db for pubkey={}".format(pub))
                signer = coring.Signer(qb64b=bytes(raw),
                                       transferable=verfer.transferable)
                signers.append(signer)

        else:
            for verfer in verfers:
                pub = verfer.qb64
                raw = self.keeper.getPri(key=pub)
                if raw is None:
                    raise ValueError("Missing prikey in db for pubkey={}".format(pub))
                signer = coring.Signer(qb64b=bytes(raw),
                                       transferable=verfer.transferable)
                signers.append(signer)

        if indices and len(indices) != len(signers):
            raise ValueError("Mismatch length indices={} and resultant signers "
                             "list={}".format(len(indices), len(signers)))

        if indexed or indices:
            sigers = []
            for i, signer in enumerate(signers):
                if indices:
                    i = indices[i]  # get index from indices
                sigers.append(signer.sign(ser, index=i))  # assigns .verfer to siger
            return sigers
        else:
            cigars = []
            for signer in signers:
                cigars.append(signer.sign(ser))  # assigns .verfer to cigar
            return cigars

**Comment by pfeairheller** [comment]
The `sigers` that are returned are instances of `Siger` class.  They have properties for retrieving the text or binary version of the signature (`qb64` and `qb64b` respectively) and the raw binary cryptographic material `raw`.

Using a `Verfer` instance that matches up with the Siger, you can verify the signature.  Here is some sample code showing how it works:

```
    with keeping.openKS(name="sid") as keeper:

        ser = (
            b'{"v":"KERI10JSON000136_","i":"Eq1XfsuS1WNK2uLnAwfJ2SwGz8MhPUDnL0Mi1yNvTQnY",'
            b'"x":"EeCCZi1R5xHUlhsyQNm_7NrUQTEKZH5P9vBomnc9AihY",'
            b'"issuer":"E4YPqsEOaPNaZxVIbY-Gx2bJgP-c7AH_K7pEE-YfcI9E","issuance":"2021-06-27T21:26:21.233257+00:00",'
            b'"d":{"id":"did:keri:Efaavv0oadfghasdfn443fhbyyr4v",'
            b'"lei":"254900OPPU84GM83MG36"}}')

        salt = coring.Salter(raw=b'0123456789abcdef').qb64
        manager = keeping.Manager(keeper=keeper, salt=salt)

        verfers, digers, cst, nst = manager.incept(salt=salt, temp=True, icount=3)  # algo default salty

        sigers = manager.sign(ser=ser, verfers=verfers)

        for idx, siger in enumerate(sigers):
            verfer = verfers[idx]
            if verfer.verify(sig=siger.raw, ser=ser):
                print("Verified sig: ", siger.qb64)

```

Which when runs outputs:

```
Verified sig:  AAMUegpWcpT6fRzbWsrTaxgAVDM3AorCMlcwM9O4SAxCQXP_2BVuRGD4ZVqpdsa5ihjhEMtTLjQv2xD9k2OG3tDg
Verified sig:  AB-igX7A7Ocj4JbjnJmIn6j7ykIGBjs8JKuec2xAKQfMeOFm2LLWK7hxVGPaqKP7jTavFhifS6AzjR6OZicqDBBg
Verified sig:  AC9MFqiZn2gAAVpfLJG7gZZQwOBPoahs7YeG7BI3C4iTQINbxHIfenAGYp6BCcSwDVa17AjCxJNETimFi3lHLMCw
```
