### ISSUE TITLE
Support for many Legal Entities using handful of Keripy instances (endpoints)

### ISSUE THREAD

**Issue by gomesc1868** [WebOfTrust/keripy#198]
**Use Case:** Provenant as a custodial service wants to serve many Legal entities and their representatives.

**Integration Pattern:** Provenant as a service provider will sign up Legal entities and their representatives and integrate with keripy behind the scenes to provide KERI core functionality. 

**Motivation:** Provenant wants to use a pool of keripy agents (ip:ports) to serve many Legal Entities and NOT one per legal entity.  

Examples of Legal Entities are:  Coke, Starbucks, Nike, Subway …

**Assumptions:**

Provenant Custodial Service running with a few instances (say 3 for now), but logically one URL endpoint(for example, https://www.provenant.com/custodial-service), behind the scene we proxy few actual instances. 

keripy running as an agent (service) with few instances with url/ports (say 3 for now)

Provenant keeps track of the keripy running instances

**Typical scenario**

Create an Entity to represent Coke in Provenant Service/storage

**Integrate with keripy** using REST APIs, Provenant needs to use one of the keripy exposed PORT endpoints (tracked by Provenant) to do the following

**POST “boot”** to init (create) the wallet for Coke (wallet name)

**PUT “boot”** to unlock the wallet for Coke (wallet name)

**POST - to trigger inception event** for the the unlocked wallet “Coke” with an alias for the first AID say, “Coke”

Trigger other events that keripy provides using the other REST APIs

As each Legal Entity signs up, Provenant manages which of the keripy PORT instances it selects to do the work described in step #2

Currently keripy is bound to a PORT once a wallet is “booted”/unlocked for a Legal Entity (wallet name in keripy world)

To use the same PORT for another Legal Entity, we need a way for the agent to unbind (“lock”) the current key store and bind (“unlock”) the key store for the other Legal Entity (alias in keripy world)

We experimented with the new GET “lock” API recently introduced in keripy 

After an agent “locked” the current entity wallet he was bound to, unlocking another wallet, threw an exception and killed the running agent service

**Comment by pfeairheller** [comment]
Closed with PR #208
