### ISSUE TITLE
Issue logging into two agents at the same time

### ISSUE THREAD

**Issue by shakedown-street** [WebOfTrust/keripy#248]
I'm getting an error that crashes `kli agent vlei` whenever I try to log into a second agent.  For example, I can create/enter a passcode for a lead root gar (5520/5620), then create an AID.  Then when I try to create another, regular, root gar (5521/5621) I'm able to create the passcode, but when I try to enter it, it always crashes my `kli agent vlei`.

I'm up to date on `development`, using python 3.10.4, and I've tried recreating my venv.  Not sure why it's happening for me but it's stopping me from moving forward on testing.

Here's the output I'm seeing when it crashes (top right terminal):

Specifically `ERR: mdb_txn_begin: Invalid argument`

![image](https://user-images.githubusercontent.com/5733448/182664618-cd53123b-c270-4878-97af-b5c7aceb78cd.png)

**Comment by pfeairheller** [comment]
Agent removed from KERIpy for WebOfTrust/KERIA
