### ISSUE TITLE
Witness Receipts Tevery Potential Bug

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#27]
Potential bug

Also, while creating the Tevery I noticed that the Kevery is dropping witness 
receipts when it places an event in the out-of-order escrow.  Is that intentional?  
Is this because in replay mode (where the witness signatures will be attached) 
the events will never be out of order and for async messages receipts are handled elsewhere?

**Comment by SmithSamuelM** [comment]
I wrapped up the multi-sig work for now. I was able to generate and publish the group inception event signed by all three controllers to 3 witnesses. When I query for the KEL from the witnesses I only get back one receipt. So something isn’t quite right saving receipts for the partially signed escrowed event but I can’t tell what.

**Comment by pfeairheller** [comment]
I have a clue in the issue of witness receipt failure on partially signed escrowed event...  I was able to capture the following exception:

```
hio: Kevery process: escrowed unverified receipt of pre= Ep4WexrfQvQjblYg9ti12cr7NpKWaXLNP5CXmq_4Zhng  sn=0 dig=E5_qNBzfkBc2kWAzGn5UUWhWUVrX4Yk1QBpVXHucygfk
                                                    
hio: Parser msg non-extraction error: Unverified receipt={'v': 'KERI10JSON000091_', 'i': 'Ep4WexrfQvQjblYg9ti12cr7NpKWaXLNP5CXmq_4Zhng', 's': '0', 't': 'rct', 'd': 'E5_qNBzfkBc2kWAzGn5UUWhWUVrX4Yk1QBpVXHucygfk'}
.         
Traceback (most recent call last):
  File "/home/pfeairheller/git_root/keripy/src/keri/core/parsing.py", line 464, in parsator
    done = yield from self.msgParsator(ims=ims,
  File "/home/pfeairheller/git_root/keripy/src/keri/core/parsing.py", line 825, in msgParsator
    kvy.processReceipt(serder=serder, cigars=cigars)                                                     
  File "/home/pfeairheller/git_root/keripy/src/keri/core/eventing.py", line 2598, in processReceipt
    raise UnverifiedReceiptError("Unverified receipt={}.".format(ked))
keri.kering.UnverifiedReceiptError: Unverified receipt={'v': 'KERI10JSON000091_', 'i': 'Ep4WexrfQvQjblYg9ti12cr7NpKWaXLNP5CXmq_4Zhng', 's': '0', 't': 'rct', 'd': 'E5_qNBzfkBc2kWAzGn5UUWhWUVrX4Yk1QBpVXHucygfk'}.
```

**Comment by SmithSamuelM** [comment]
May be fixed with this pull request

**Comment by SmithSamuelM** [comment]
Highly likely fixed with this pull request  https://github.com/WebOfTrust/keripy/pull/50
