### ISSUE TITLE
Unify command line argument for incept and rotate commands

### ISSUE THREAD

**Issue by pfeairheller** [WebOfTrust/keripy#274]
Current inception command accepts only a file of configuration information for the new identifier and rotate command accepts only arguments specified individually on the command line.

We need to have both commands support both individual arguments on the command line and a configuration file, with individual argument overriding anything in the configuration file.

**Comment by kentbull** [comment]
Came across a related issue when working on this: #412 and related PR #413.

**Comment by kentbull** [comment]
This looks like it can be closed now.

**Comment by pfeairheller** [comment]
Done by @kentbull
