### ISSUE TITLE
alice-bob-agent.sh : POST ".../oobi/Alice" gets "405 Method Not Allowed"

### ISSUE THREAD

**Issue by haroldcarr** [WebOfTrust/keripy#285]
Same thing for

```
curl -s -X POST "http://localhost:5723/oobi/Bob" ...
```

thus the following two return empty lists:

```
echo "Alice's Contacts:"
curl -s -X GET "http://localhost:5623/contacts" -H "accept: */*" | jq
echo "Bob's Contacts:"
curl -s -X GET "http://localhost:5723/contacts" -H "accept: */*" | jq
```

I imagine the script is out-of-date.  What needs to be updated for this to work?

**Comment by pfeairheller** [comment]
The OOBI endpoint no longer needs an alias.  I was fixing some other scripts in PR #286 so pushed this fix as well.  This issue will close when that is merged.
