### ISSUE TITLE
Keri agent crashes with lmdb MDB_MAP_FULL error

### ISSUE THREAD

**Issue by psteniusubi** [WebOfTrust/keripy#287]
I was using Keep to walk through Root GAR inception. Starting with empty database with ~/.keri folder removed. Was able to complete most of the steps but while attempting to setup multi-sig group the Keri agent crashed with lmdb MDB_MAP_FULL error. Restarting Keri agent would not help. Keri agent was started with command "kli agent vlei"

![image](https://user-images.githubusercontent.com/17900263/187288007-672bccd7-4da2-44dc-abb4-6241f11449ea.png)

I have attached a backup of the database. Unfortunately I have lost the passcodes. One of the database files has about 10 mb size:

10481664 elo 26 10:37 .keri/db/keep-root-gar-5621/data.mdb

[bak-220826.zip](https://github.com/WebOfTrust/keripy/files/9447688/bak-220826.zip)

**Comment by pfeairheller** [comment]
Agent removed from KERIpy for WebOfTrust/KERIA
