### ISSUE TITLE
How to Verify signed message from a separate code

### ISSUE THREAD

**Issue by abhinavb1293** [WebOfTrust/keripy#29]
I want to do verification, I have one issuer application that signs my credentials code:
sig = keeping.Manager(keeper=kpr, salt=salt).sign(bytes(json.dumps(data),'utf-8'),pubs=digers,verfers=verfers)

How can I verify the signature generated above in a separate application?

**Comment by pfeairheller** [comment]
You would need to have the KEL of the signer loaded in the separate application.  In addition, the separate application would need to be given the sequence number and digest of the event at which the data was signed (so it can load the exact set of keys used to sign the data).

Assuming you have loaded the KEL of the signer into your DB and you have a handle to your database, you can use some of the code from the `verify` method in the Habitat class to verify the signature on your data.  

db is Baser instance of database
prefixer is Prefixer instance of signer's identifier
sn is sequence number of KEL when data was signed
diger is Diger instance of the event in the KEL when the data was signed
sigers is a list of Siger instances representing the signatures being verified (a list to account for multi-sig)
data is the signed data

```
            
            sdig = db.getKeLast(key=snKey(pre=prefixer.qb64b,
                                               sn=sn))
            if sdig is None:
                # receipter's est event not yet in receipters's KEL
                raise UnverifiedProofError("key event sn {} for pre {} is not yet in KEL"
                                           "".format(seqner.sn, prefixer.qb64))


            # retrieve last event itself of receipter est evt from sdig
            sraw = db.getEvt(key=dgKey(pre=prefixer.qb64b, dig=bytes(sdig)))
           
            # assumes db ensures that sraw must not be none because sdig was in KE
            sserder = Serder(raw=bytes(sraw))
            if not sserder.compare(diger=diger):  # endorser's dig not match event
                raise ValidationError("Bad proof sig group at sn = {}"
                                      " for ksn = {}."
                                      "".format(seqner.sn, sserder.ked))

            # verify sigs
            sverfers = sserder.verfers
            if not sverfers:
                raise ValidationError("Invalid key state endorser's est. event"
                                      " dig = {} for ksn from pre ={}, "
                                      "no keys."
                                      "".format(diger.qb64, prefixer.qb64))

            for siger in sigers:
                if siger.index >= len(sverfers):
                    raise ValidationError("Index = {} too large for keys."
                                          "".format(siger.index))
                siger.verfer = sverfers[siger.index]  # assign verfer
                if not siger.verfer.verify(siger.raw, data):  # verify each sig
                    return False

            return True
```
