### ISSUE TITLE
Support for Weighted Thresholds in CLI

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#335]
- [ ]  add command line arg for json sith (jsith? json?) in order to accept JSON representation of sith  (signing threshold) for cli input

See Tholder.json property and Tholder._processSith method for round tripping to from json version of sith.

## List of weights
```json
'["1/2", "1/2", "1/4", "1/4", "1/4", "0"]'
```
 round trips as
```json
'["1/2", "1/2", "1/4", "1/4", "1/4", "0"]'
```

## List of list of weights

```json
'[["1/2", "1/2", "1/4", "1/4", "1/4"]]'
```

round trips as single list of weights
```json
'["1/2", "1/2", "1/4", "1/4", "1/4", "0"]'
```

## list of lists of weights
```json
'[["1/2", "1/2", "1/4", "1/4", "1/4"], ["1/1", "1"]]'
```

round trips as list of lists of weights
```json
'[["1/2", "1/2", "1/4", "1/4", "1/4"], ["1", "1"]]'
```

Note improper fractions converted to in str int

**Comment by pfeairheller** [comment]
Weighted thresholds now supported from the kli
