### ISSUE TITLE
Add subclass GroupHab of Hab to better encapsulate differences

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#353]
There is a lot of code in Hab of the form
if self.mhab ....

to execute group hab specific code.  this is begging to be put in a sub class that has the GroupHab code.

Only the subclass GroupHab would then have a .mhab  .merfers .migers .smids .rmids where all the group specific stuff is going

**Comment by pfeairheller** [comment]
Closed with PR #438
