### ISSUE TITLE
Direct mode Agent Support

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#357]
A question came up about support for direct mode.

There are two main use cases for  direct mode. 

1- direct mode on both ends
2- direct mode on one end and indirect mode on the other end

Currently direct mode support involves a dedicated tcp connection with direct mode both ends.  

One way to expand direct mode support is to leverage the current indirect mode agent code.
Each witness in indirect mode also has an agent API with a mailbox.  We could modify the agent api to represent just the direct mode controller (i.e. a controller with no witnesses). Instead of a witness OOBI to find the endpoint, one just publishes a controller OOBI. 

Anyone wanting to get the KEL of the controller just hits the endpoint published by the controller OOBI.  Exchange messages use the SSE + push interface of the Agent API.

**Comment by pfeairheller** [comment]
Agent removed from KERIpy for WebOfTrust/KERIA
