### ISSUE TITLE
Cannot start witness(es) for local AID inception

### ISSUE THREAD

**Issue by tosirisuk** [WebOfTrust/keripy#456]
This issue was taken from the KERIpy slack channel. The thread is [here](https://keriworld.slack.com/archives/C025C56K2SC/p1677507611116489).

I have set up 5 witnesses already. Then, I tried to incept a local AID (says Alice's AID)
I did two steps.

The first step is to initialize the Key Store `ks` using the `kli init` command, and I passed the `--config-file` during the `init `event as shown below (to initialize the key store to know about my 5 witnesses)
```
{
  "dt": "2023-02-26T12:57:59.823350+00:00",
  "iurls": [
    "http://13.213.0.148:5631/oobi/BC7qjybOGR7-UPVp-R-gqPmeeFY2eI6FYr-OE2OI8iMX",
    "http://13.213.0.148:5633/oobi/BLQOLhl3SAhuBEWbNT3CzyU2u4gesbpKx70Tzvkrk-1Y",
    "http://13.213.0.148:5635/oobi/BAHVSvATS6N8fQfV-UfJB_xZXzRuEL5mX7cWKdxNKVzK",
    "http://13.213.0.148:5637/oobi/BBmSeiRdPwwH3Ph5VSPJXFa1ub2zfYiR1XS7LUqGyJ_g",
    "http://13.213.0.148:5639/oobi/BMF2DG6OJ-En0Rb2UqSfZ0g5VtruxhIIrOE-XNcBprpR"
  ]
}
```

The output of the `kli init` command is
```
KERI Keystore created at: /home/ubuntu/.keri/ks/QAR-ALICE
KERI Database created at: /home/ubuntu/.keri/db/QAR-ALICE
KERI Credential Store created at: /home/ubuntu/.keri/reg/QAR-ALICE
        aeid: BN7nMtdIVbhhY8c6Vslof3AhvaVT1KQY2scX_XLZsW9t

Loading 5 OOBIs...
http://13.213.0.148:5631/oobi/BC7qjybOGR7-UPVp-R-gqPmeeFY2eI6FYr-OE2OI8iMX succeeded
http://13.213.0.148:5633/oobi/BLQOLhl3SAhuBEWbNT3CzyU2u4gesbpKx70Tzvkrk-1Y succeeded
http://13.213.0.148:5635/oobi/BAHVSvATS6N8fQfV-UfJB_xZXzRuEL5mX7cWKdxNKVzK succeeded
http://13.213.0.148:5637/oobi/BBmSeiRdPwwH3Ph5VSPJXFa1ub2zfYiR1XS7LUqGyJ_g succeeded
http://13.213.0.148:5639/oobi/BMF2DG6OJ-En0Rb2UqSfZ0g5VtruxhIIrOE-XNcBprpR succeeded
```

However, for this `incept` step, when I ran the `kli incept` command and pass the `--file` as shown below
```
{
  "transferable": true,
  "wits": [
    "BC7qjybOGR7-UPVp-R-gqPmeeFY2eI6FYr-OE2OI8iMX",
    "BLQOLhl3SAhuBEWbNT3CzyU2u4gesbpKx70Tzvkrk-1Y",
    "BAHVSvATS6N8fQfV-UfJB_xZXzRuEL5mX7cWKdxNKVzK",
    "BBmSeiRdPwwH3Ph5VSPJXFa1ub2zfYiR1XS7LUqGyJ_g",
    "BMF2DG6OJ-En0Rb2UqSfZ0g5VtruxhIIrOE-XNcBprpR"
  ],
  "toad": 5,
  "icount": 1,
  "ncount": 1,
  "isith": "1",
  "nsith": "1"
}
```
It shows an error that it cannot receive any receipts from any of 5 witnesses.
`ERR: unable to find a valid endpoint for witness BC7qjybOGR7-UPVp-R-gqPmeeFY2eI6FYr-OE2OI8iMX`
```
Alias:  Alice Alicia
Identifier: EOBA19qSkKfflSMXj28FlV8i5JwTkYSUX4vZjeLSsMLV
Seq No: 0

Witnesses:
Count:          5
Receipts:       0
Threshold:      5

Public Keys:
        1. DD5K6t_-cV2cijPpXAU6Ajs_GI6tYVmtbhDE35eX08BL
```

**Therefore, how should I start the witness(es) properly for the inception of a local AID?**

I use the configuration files for the witness(es) initialization.
```
{
  "transferable": false,
  "wits": [],
  "icount": 1,
  "ncount": 1,
  "isith": "1",
  "nsith": "1"
}
```
```
witness_0.json
{
    "witness_0": {
        "dt": "2023-02-24T12:57:59.823350+00:00",
        "curls": [
            "tcp://13.213.0.148:5632/",
            "http://13.213.0.148:5631/"
        ]
    },
    "dt": "2023-02-24T12:57:59.823350+00:00",
    "iurls": []
}
```
```
witness_1.json
{
    "witness_1": {
        "dt": "2023-02-24T12:57:59.823350+00:00",
        "curls": [
            "tcp://13.213.0.148:5634/",
            "http://13.213.0.148:5633/"
        ]
    },
    "dt": "2023-02-24T12:57:59.823350+00:00",
    "iurls": []
}
```

and so on for `witness_2.json`, `witness3.json`, and `witness_4.json`

**Comment by kentbull** [comment]
It looks to me like the `kli witness start` command is missing the arguments `config-dir` and `config-file`.
PR incoming.

**Comment by tosirisuk** [comment]
@kentbull PR #457  does not fix the issue with the local AID inception (says Alice's AID inception). 

After carefully investigating, I think the issue is not just about how I started the `kli witness`.
I tried set up `kli witness demo` remotely at `13.229.205.28` , you can access those 6 witnesses (`wan`, `wil` `wes`, …) , e.g. at http://13.229.205.28:5642/oobi/BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha/controller
However, when I tried to init (which the oobi can resolve the above-mentioned 6 witnesses) and incept Alice's local AID, it failed to retrieve the receipts from any of the witnesses.
Therefore, I think the problem of the issue is not about how I set up the witness(es). Is any security configuration needed to be set apart from the `tcp` and `http` ports?

**Comment by jruizaranguren** [comment]
@kentbull, could `kli witness demo` have the same problem?. [I'm testing your tutorial](https://kentbull.com/2023/01/27/keri-tutorial-series-kli-sign-and-verify-with-heartnet/), and I'm getting the same `ERR: unable to find a valid endpoint for witness BM35JN8XeJSEfpxopjn5jr7tAHCE5749f0OobhMLCorE` error.

**Comment by kentbull** [comment]
The Op's answer is correct, you have a config file problem. It's likely that your config file is not being detected and instead a blank file is being created and used by the KLI.

When I posted my earlier comment I was incorrect in thinking that there was a need to change the config directory. You can use the default paths.

One way to troubleshoot this is to look at the directory tree under where you run 'kli witness demo' from and watch to see if there is a new, blank config file created with the same name that you pass in to the "--config-file" argument. If so then your path to that file is incorrect and needs to reflect where the file is located on the file system.

**Comment by jruizaranguren** [comment]
@kentbull it seems to be the case, but I'm struggling to fix it.  This is the file structure before invoking `kli incept`:


<pre><font color="#12488B"><b>.keri</b></font>
├── <font color="#12488B"><b>allie</b></font>
│   └── <span style="background-color:#12488B"><font color="#D0CFCC">allie_ks</font></span>
│       ├── data.mdb
│       └── lock.mdb
├── <font color="#12488B"><b>brett</b></font>
│   └── <span style="background-color:#12488B"><font color="#D0CFCC">brett_ks</font></span>
│       ├── data.mdb
│       └── lock.mdb
├── <font color="#12488B"><b>heartnet</b></font>
│   └── <font color="#12488B"><b>keri</b></font>
│       └── <font color="#12488B"><b>cf</b></font>
│           ├── <font color="#26A269"><b>allie-witness-oobis.json</b></font>
│           └── <font color="#26A269"><b>brett-witness-oobis.json</b></font>
└── <font color="#12488B"><b>scripts</b></font>
    └── <font color="#12488B"><b>keri</b></font>
        └── <font color="#12488B"><b>cf</b></font>
            └── <font color="#12488B"><b>main</b></font>
                ├── <font color="#26A269"><b>wan.json</b></font>
                ├── <font color="#26A269"><b>wes.json</b></font>
                ├── <font color="#26A269"><b>wil.json</b></font>
                ├── <font color="#26A269"><b>wit.json</b></font>
                ├── <font color="#26A269"><b>wub.json</b></font>
                └── <font color="#26A269"><b>wyz.json</b></font>
</pre>

After that, I have tried several options for `--config` (.keri, .keri/heartnet, .keri/allie) with no success, such as:

```
kli incept \
      --name allie_ks \
      --base .keri/allie \  
      --alias magic-pencil \
      --config .keri/heartnet \
      --file .keri/allie/magic-pencil.json
```

What would be the correct value for `config`?

**Comment by kentbull** [comment]
I'd have to read the source code again, though it looks like your `--base` argument is wrong. Try not using a base or a config file for `kli incept`. Feel free to ping me on the WebOfTrust Discord here: https://discord.com/invite/edGDD632tP
You can @ me from the #edu channel.

**Comment by jruizaranguren** [comment]
I tried three things.

* not `--base` argument. Error:

```bash
 Keystore must already exist, exiting
```
* not `--file` argument. Error:

```bash
ERR: Required arg transferable not present when config file not specified
```

* not `--config` argument. Error:

```bash
Waiting for witness receipts...
ERR: unable to find a valid endpoint for witness BBilc4-L3tFUnfM_wJr4S4OJanAv_VmF_dJNN6vkf2Ha
```
:sob: , moving to discord (and probably to code inspect) :smile:
