### ISSUE TITLE
Add Support for Habery  which is manager of multiple habitats

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#46]
A given keystore and KEL LMDB database may be shared by multiple Habitats. Each Habitat has a controller prefix AID.  By default currently the name of the keystore and key db directory path includes the name of the first Habitat upon creation, but does not need to be that way. For DB shared by multiple habitats the db file dir path should be a name that represents the component or application which could be different from any of the associated Habitats.  So we need to have a naming convention and also setup the Doers etc so that it follows that convention when multiple Habitats share the same DBs. 

If Habitats are setup asynchronously then there might be that case where in order to use the same database a later habitat with the same name but different AID is created that clobbers a previous Habitat with same name.

An example is the MultiSig setup.

**Comment by SmithSamuelM** [comment]
Habery owns the database KEL and keystore that is shared by all the habitats

**Comment by pfeairheller** [comment]
Complete by @SmithSamuelM
