### ISSUE TITLE
New version release request: coring.Ids.dollar to coring.Saids.dollar broke KASLcred

### ISSUE THREAD

**Issue by kentbull** [WebOfTrust/keripy#479]
Can we get another KERIpy release any time soon, v1.0.1? Sam’s change in [this commit](https://github.com/WebOfTrust/keripy/commit/379c49e11cd02c640a4fa47484d94d14f28b4f8c#diff-f55a5aa13d6e2d04f9c6a12d9738b139cc2e0f91bfabde451621a8875ee04737R3188) of coring.Ids.dollar to coring.Saids.dollar broke KASLcred. His change was on April 6th, six days after the 1.0.0 Pypi release on 3/31/23.

**Comment by SmithSamuelM** [comment]
That change was to the dev branch not the main release branch

**Comment by kentbull** [comment]
Oh, I hit this locally because I run locally against the dev branch of KERIpy, so KASLcred only broke for me it looks like. Anyone using KASLcred <=0.0.8 would not hit this until the dev change is merged to main.

We could set up a status indicator in KERIpy's readme linked to dependent repositories triggered on each build.
