### ISSUE TITLE
ReadTheDocs Keripy build broken

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#489]
When trying to update the build of sphinx on readthedocs get the following error.
In addition the latest configuration is setup to build from the master branch which we no longer have. So need to change latest to build from main or development

Error

Problem in your project's configuration. Invalid "build.tools.python": expected one of (2.7, 3.6, 3.7, 3.8, 3.9, 3.10, 3.11, pypy3.7, pypy3.8, pypy3.9, miniconda3-4.7, mambaforge-4.10, 3), got 3.10.4
git clone --no-single-branch --depth 50 https://github.com/WebOfTrust/keripy.git .
git checkout --force origin/development
git clean -d -f -f

**Comment by pfeairheller** [comment]
Done
