### ISSUE TITLE
search spins forever in the readthedocs :  https://keripy.readthedocs.io

### ISSUE THREAD

**Issue by henkvancann** [WebOfTrust/keripy#566]
the search doesn’t work in the readthedocs :  https://keripy.readthedocs.io try “vcp”
===
Philip Feairheller to You (Direct Message) (5 Sep 2023, 15:49)
I never even tried the search, but you are right, it just spins forever.  Since we replicated the RTD approach across all repos and started with KERIpy, let’s try to solve it in KERIpy and then propagate the fix to the rest.   Can you create an issue in keripy and we’ll start from there?
 
Philip Feairheller to You (Direct Message) (5 Sep 2023, 15:51)
This is the error I’m getting and no network call is initiated:

Uncaught ReferenceError: jQuery is not defined
Might be a quick fix
 
You to Philip Feairheller (Direct Message) (5 Sep 2023, 15:53)
Yes I will, the search in Sphinx and Readthedocs works, it delivers a pop-up where you can search:
https://readthedoc-test00.readthedocs.io/en/latest/guides/searching-with-readthedocs.html?#enable-search-as-you-type-in-your-documentation
So indeed something might not be properly configured yet.

**Comment by daidoji** [comment]
This seems like its fixed.
