### ISSUE TITLE
Add weights to clauses in fractionally weighted signing threshold

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#579]
Currently, the fractionally weighted signing threshold supports logically ANDed clauses of fractional weight lists. To satisfy the threshold, each clause's weights must sum to >= 1 in order to make the clause's satisfaction TRUE and then the truth values of the clauses are ANDed together to get the truth value for the whole threshold. This works with only one clause or only a list of weights which is trivially equivalent to 1 clause.

A use case was brought up by @rodolfomiranda  where each member of a distributed multi-sig group would like to use a single controller (non-distributed) multi-sig AID to contribute to that distributed multi-sig group where each member multi-sig AID is controlled by multiple devices where each device may contribute a signing key.

As an example suppose we logically have a 2 of 3 multisig group where each member is a 2 of 3.  To directly implement this as a single group multi-sig threshold using clauses  we would need new syntax  that supports combining the clauses not with AND but with a fractional weights on each clause.  A possible syntax could be something like.

```python
["1/2"* ["1/2", "1/2", "1/2"], "1/2"*["1/2", "1/2","1/2"], "1/2"*["1/2", "1/2", "1/2"]]
```

With the current syntax the closest we could come would be the following

```python
[["1/2", "1/2", "1/2"], ["1/2", "1/2","1/2"], ["1/2", "1/2", "1/2"]]
```

Which would be a 3 of 3 of 2 of 3s not a 2 of 3 of 2 of 3s.

This requires changing the Tholder object.

Need unambiguous new syntax that satisfies:

- backwards compatible with existing syntax
- can be expressed as a python compilable object (list for example) that can be encoded as a JSON string that is convertable to a  CESR encoded string .

Currently for example.

```
b'4AAGA1s2c1s2c1s4c1s4c1s4a1c1'
```
and 

```
[["1/2", "1/2", "1/4", "1/4", "1/4"], ["1", "1"]]
```
are two different representations of the same threshold

I would have to look at the existing parsing logic to see what is a clean backwards compatible syntax that is relatively easy to parse.

For example in the following the first element of the clause of clauses is the combining operator and when it is the `*` then the first element of each interior clause is the weight for the remaining elements that form the clause

```
[ "*", ["1/2", "1/2", "1/2", "1/2"], ["1/2", "1/2", "1/2", "1/2"], ["1/2", "1/2", "1/2", "1/2"]]
```

Building on this syntax  we could then express the current ANDed logic as follows.

```
[ "&", ["1/2", "1/2", "1/2"], ["1/2", "1/2", "1/2"], ["1/2", "1/2", "1/2"]]
```

And if there is no combination operator in a clause of clauses then by default its ANDed so we have backwards compatiblity.

Then in the future  we could  add other weighted combination operators to  weighted thresholds besides simple sum of weights.

Need to add CESR encoding such as `w` to indicate weighted clauses.

**Comment by rodolfomiranda** [comment]
I like the idea of having the first element, if exist, as an operator or modifier parameter. Additionally, each clause can be evaluated independently, and processing the complete threshold can be achieved recursively, ideal for recursive functions in python.
