### ISSUE TITLE
IPEX bug in recent update

### ISSUE THREAD

**Issue by nkongsuwan** [WebOfTrust/keripy#583]
In the recent IPEX update to [scripts/demo/credentials/single-issuer.sh](https://github.com/WebOfTrust/keripy/blob/development/scripts/demo/credentials/single-issuer.sh), I get a bug `ERR: 'Hab' object has no attribute 'mhab' ` after I ran `kli ipex grant`.

**Comment by m00sey** [comment]
@pfeairheller I'll work with you to retest this.
