### ISSUE TITLE
[Minor] scripts/demo/credentials and scripts/demo/vLEI direcotories don't seem to run anymore or match the README.md in the demo directory

### ISSUE THREAD

**Issue by daidoji** [WebOfTrust/keripy#665]
## Description

Scripts in the `scripts/demo/credentials` and `scripts/demo/vLEI` directories don't seem to run anymore or match up to running with the info of what is in the README.md (many of these scripts seem to rely on credentials I can't quite find in the repository and on the vLEI server serving data oobis).  They don't run in github actions.

## Issue
Probably the README should be cleaned up and these scripts either deleted or adapted to run in the integration tests to help new users differentiate between user error and potential issues that may arise from the kli commands.

This relates to #653 in that its another gotcha for users attempting to use the demos in the scripts directory when learning kli commands.

**Comment by pfeairheller** [comment]
I have a fix for this on the way.

**Comment by pfeairheller** [comment]
Fixed with #675
