### ISSUE TITLE
Python 3.12 more strict on Regex: SyntaxWarning: invalid escape sequence '\-'  B64REX = b'^[A-Za-z0-9\-\_]*\Z' in src/keri/core/coring.py:142

### ISSUE THREAD

**Issue by kentbull** [WebOfTrust/keripy#690]
Python 3.12 is more strict on regular expressions.
In src/keri/core/coring.py:142 the following regular expression shows a syntax warning in my console every time I run a witness:
```python
src/keri/core/coring.py:142: SyntaxWarning: invalid escape sequence '\-'
  B64REX = b'^[A-Za-z0-9\-\_]*\Z'
```

Some solutions here are:
1. Use a raw string (backslashes not needed):
```python
B64REX = rb'^[A-Za-z0-9-_]*\Z'
```
2. escape the slash
```python
B64REX = b'^[A-Za-z0-9\\-_]*\\Z'
```

**Comment by SmithSamuelM** [comment]
```pythonh
b'^[A-Za-z0-9_-]*\Z'
```

Should work.  I dont have any problems with 3.12

As long as the minus - is the first or last character in a group it doesn’t have to be escaped

**Comment by daidoji** [comment]
@kentbull this has been fixed.
