### ISSUE TITLE
Deprecate randomNonce() function in coring.py

### ISSUE THREAD

**Issue by SmithSamuelM** [WebOfTrust/keripy#739]
Nonces only need 128 bits of entropy.  a Salt is enough not a seed
Just use Salter().qb64.

```python
def randomNonce():
    """ Generate a random ed25519 seed and encode as qb64

    Returns:
        str: qb64 encoded ed25519 random seed
    """
    preseed = pysodium.randombytes(pysodium.crypto_sign_SEEDBYTES)
    seedqb64 = Matter(raw=preseed, code=MtrDex.Ed25519_Seed).qb64
    return seedqb64
```

If truly need 256 bits of entropy for a Nonce then we should create Seeder Class that generates by default a random seed
using code = MtrDex.Ed25519_Seed

**Comment by lenkan** [comment]
I guess we should take the same action in signify-ts: https://github.com/WebOfTrust/signify-ts/blob/development/src/keri/app/coring.ts#L13-L17 ?
